import type {
  NurseStats,
  NurseQueuePatient,
  NurseVitalRecord,
  NursingTask,
  AdmissionRecord,
  NursingActivity,
} from '../types/nurse';

export const NURSE_STATS: NurseStats = {
  assignedPatients: 14,
  patientsWaiting: 6,
  admissionsToday: 5,
  tasksPending: 8,
  criticalAlerts: 1,
  vitalsCompleted: 22,
};

export const NURSE_PATIENT_QUEUE: NurseQueuePatient[] = [
  {
    id: 'nq-01',
    patientId: 'MC-000001',
    patientName: 'Abebe Kebede',
    patientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    age: 38,
    gender: 'Male',
    roomBed: 'Room 204 • Bed A',
    doctorName: 'Dr. Hana Mengistu',
    condition: 'Hypertension Crisis / Post-op Obs',
    priority: 'Urgent',
    status: 'Vitals Due',
    admissionTime: 'Today, 08:30 AM',
    allergies: ['Penicillin', 'Sulfa drugs'],
    vitalsSummary: {
      bp: '142/92',
      hr: 82,
      temp: 37.2,
      spo2: 97,
    },
  },
  {
    id: 'nq-02',
    patientId: 'MC-000005',
    patientName: 'Tigist Assefa',
    patientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    age: 26,
    gender: 'Female',
    roomBed: 'Room 205 • Bed B',
    doctorName: 'Dr. Hana Mengistu',
    condition: 'Acute Asthma Exacerbation',
    priority: 'Critical',
    status: 'In Care',
    admissionTime: 'Today, 09:15 AM',
    allergies: ['Aspirin', 'NSAIDs'],
    vitalsSummary: {
      bp: '128/84',
      hr: 104,
      temp: 37.8,
      spo2: 93,
    },
  },
  {
    id: 'nq-03',
    patientId: 'MC-000002',
    patientName: 'Sara Desta',
    patientAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    age: 29,
    gender: 'Female',
    roomBed: 'Room 202 • Bed A',
    doctorName: 'Dr. Hana Mengistu',
    condition: 'Atypical Angina Evaluation',
    priority: 'Normal',
    status: 'Bed Assigned',
    admissionTime: 'Today, 07:50 AM',
    allergies: ['Codeine'],
    vitalsSummary: {
      bp: '118/76',
      hr: 68,
      temp: 36.7,
      spo2: 99,
    },
  },
  {
    id: 'nq-04',
    patientId: 'MC-000003',
    patientName: 'Dawit Bekele',
    patientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    age: 45,
    gender: 'Male',
    roomBed: 'Room 206 • Bed C',
    doctorName: 'Dr. Michael Chen',
    condition: 'Type 2 Diabetes / Glycemic Spike',
    priority: 'Urgent',
    status: 'Waiting',
    admissionTime: 'Today, 10:00 AM',
    allergies: [],
    vitalsSummary: {
      bp: '135/88',
      hr: 78,
      temp: 36.9,
      spo2: 98,
    },
  },
  {
    id: 'nq-05',
    patientId: 'MC-000006',
    patientName: 'Kassahun Tolessa',
    patientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    age: 52,
    gender: 'Male',
    roomBed: 'Room 201 • Bed B',
    doctorName: 'Dr. Sarah Johnson',
    condition: 'Post-Op Day 2 Laparotomy',
    priority: 'Normal',
    status: 'In Care',
    admissionTime: 'Yesterday, 14:00 PM',
    allergies: ['Latex'],
    vitalsSummary: {
      bp: '124/80',
      hr: 72,
      temp: 37.0,
      spo2: 98,
    },
  },
];

export const RECENT_VITALS: NurseVitalRecord[] = [
  {
    id: 'vit-01',
    patientId: 'MC-000005',
    patientName: 'Tigist Assefa',
    patientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 205 • Bed B',
    bp: '128/84',
    hr: 104,
    temp: 37.8,
    spo2: 93,
    rr: 24,
    status: 'Critical',
    recordedAt: '12 mins ago',
    notes: 'Tachycardia and mild tachypnea. Nebulization salbutamol initiated per order.',
  },
  {
    id: 'vit-02',
    patientId: 'MC-000001',
    patientName: 'Abebe Kebede',
    patientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 204 • Bed A',
    bp: '142/92',
    hr: 82,
    temp: 37.2,
    spo2: 97,
    rr: 18,
    status: 'Warning',
    recordedAt: '35 mins ago',
    notes: 'Mild hypertension noted on repeat. Oral antihypertensive administered at 09:00.',
  },
  {
    id: 'vit-03',
    patientId: 'MC-000002',
    patientName: 'Sara Desta',
    patientAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 202 • Bed A',
    bp: '118/76',
    hr: 68,
    temp: 36.7,
    spo2: 99,
    rr: 16,
    status: 'Normal',
    recordedAt: '50 mins ago',
    notes: 'Hemodynamically stable. Resting comfortably.',
  },
  {
    id: 'vit-04',
    patientId: 'MC-000003',
    patientName: 'Dawit Bekele',
    patientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 206 • Bed C',
    bp: '135/88',
    hr: 78,
    temp: 36.9,
    spo2: 98,
    rr: 17,
    status: 'Normal',
    recordedAt: '1 hour ago',
    notes: 'Fingerstick blood glucose was 164 mg/dL before breakfast.',
  },
  {
    id: 'vit-05',
    patientId: 'MC-000006',
    patientName: 'Kassahun Tolessa',
    patientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 201 • Bed B',
    bp: '124/80',
    hr: 72,
    temp: 37.0,
    spo2: 98,
    rr: 16,
    status: 'Normal',
    recordedAt: '2 hours ago',
    notes: 'Surgical wound site clean, dry, and intact. Pain scale 2/10.',
  },
];

export const NURSING_TASKS: NursingTask[] = [
  {
    id: 'tsk-01',
    patientId: 'MC-000005',
    patientName: 'Tigist Assefa',
    patientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 205 • Bed B',
    title: 'Administer medication: IV Hydrocortisone 100mg stat',
    type: 'Administer Medication',
    dueTime: 'Due Now',
    priority: 'High Priority',
    completed: false,
    notes: 'Order confirmed by Dr. Hana Mengistu.',
  },
  {
    id: 'tsk-02',
    patientId: 'MC-000001',
    patientName: 'Abebe Kebede',
    patientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 204 • Bed A',
    title: 'Check vital signs & repeat blood pressure monitor',
    type: 'Check Vital Signs',
    dueTime: '10:30 AM',
    priority: 'Urgent',
    completed: false,
    notes: 'Target BP < 135/85 mmHg post-dose.',
  },
  {
    id: 'tsk-03',
    patientId: 'MC-000002',
    patientName: 'Sara Desta',
    patientAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 202 • Bed A',
    title: 'Prepare patient for 12-lead Electrocardiogram (ECG)',
    type: 'Prepare Patient',
    dueTime: '11:00 AM',
    priority: 'Normal',
    completed: false,
    notes: 'Portable ECG technician notified.',
  },
  {
    id: 'tsk-04',
    patientId: 'MC-000003',
    patientName: 'Dawit Bekele',
    patientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 206 • Bed C',
    title: 'Update nursing notes & dietary intake log',
    type: 'Update Nursing Notes',
    dueTime: '11:30 AM',
    priority: 'Normal',
    completed: true,
    notes: 'Diabetic meal tolerated well with zero nausea.',
  },
  {
    id: 'tsk-05',
    patientId: 'MC-000006',
    patientName: 'Kassahun Tolessa',
    patientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    roomBed: 'Room 201 • Bed B',
    title: 'Wound dressing inspection and surgical drain measurement',
    type: 'Wound Dressing',
    dueTime: '12:00 PM',
    priority: 'Normal',
    completed: false,
    notes: 'Jackson-Pratt drain output: 25mL serosanguinous.',
  },
];

export const RECENT_ADMISSIONS: AdmissionRecord[] = [
  {
    id: 'adm-01',
    patientId: 'MC-000005',
    patientName: 'Tigist Assefa',
    patientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    age: 26,
    gender: 'Female',
    room: 'Room 205',
    bed: 'Bed B',
    admissionTime: 'Today, 09:15 AM',
    assignedDoctor: 'Dr. Hana Mengistu',
    status: 'Admitted',
    diagnosis: 'Severe Acute Bronchospasm',
  },
  {
    id: 'adm-02',
    patientId: 'MC-000003',
    patientName: 'Dawit Bekele',
    patientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    age: 45,
    gender: 'Male',
    room: 'Room 206',
    bed: 'Bed C',
    admissionTime: 'Today, 08:45 AM',
    assignedDoctor: 'Dr. Michael Chen',
    status: 'Admitted',
    diagnosis: 'Hyperglycemic Hyperosmolar State',
  },
  {
    id: 'adm-03',
    patientId: 'MC-000007',
    patientName: 'Bethlehem Tadesse',
    patientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    age: 31,
    gender: 'Female',
    room: 'Room 203',
    bed: 'Bed A',
    admissionTime: 'Today, 07:30 AM',
    assignedDoctor: 'Dr. Sarah Johnson',
    status: 'In Triage',
    diagnosis: 'Acute Gastroenteritis with Dehydration',
  },
  {
    id: 'adm-04',
    patientId: 'MC-000008',
    patientName: 'Yosef Haile',
    patientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    age: 63,
    gender: 'Male',
    room: 'Room 207',
    bed: 'Bed A',
    admissionTime: 'Today, 06:50 AM',
    assignedDoctor: 'Dr. Hana Mengistu',
    status: 'Admitted',
    diagnosis: 'Congestive Heart Failure Exacerbation',
  },
];

export const RECENT_NURSING_ACTIVITIES: NursingActivity[] = [
  {
    id: 'act-01',
    action: 'Emergency Nebulization Delivered',
    patientName: 'Tigist Assefa',
    patientId: 'MC-000005',
    roomBed: 'Room 205 • Bed B',
    time: '15 mins ago',
    type: 'Medication',
    details: 'Salbutamol 5mg via oxygen mask at 6L/min. SpO2 improved from 91% to 94%.',
  },
  {
    id: 'act-02',
    action: 'Vitals Logged & Triage Flagged',
    patientName: 'Abebe Kebede',
    patientId: 'MC-000001',
    roomBed: 'Room 204 • Bed A',
    time: '38 mins ago',
    type: 'Vitals',
    details: 'BP elevated at 142/92. Dr. Mengistu alerted; antihypertensive given.',
  },
  {
    id: 'act-03',
    action: 'Inpatient Ward Admission Check-in',
    patientName: 'Dawit Bekele',
    patientId: 'MC-000003',
    roomBed: 'Room 206 • Bed C',
    time: '1 hour ago',
    type: 'Admission',
    details: 'Admitted from emergency transfer. ID wristband placed and allergy verified.',
  },
  {
    id: 'act-04',
    action: 'IV Antibiotic Infusion Started',
    patientName: 'Sara Desta',
    patientId: 'MC-000002',
    roomBed: 'Room 202 • Bed A',
    time: '1 hr 40 mins ago',
    type: 'Medication',
    details: 'IV Cefazolin 1g in 100mL NS infused over 30 mins with no adverse reaction.',
  },
  {
    id: 'act-05',
    action: 'Shift Handover & Care Plan Updated',
    patientName: 'Kassahun Tolessa',
    patientId: 'MC-000006',
    roomBed: 'Room 201 • Bed B',
    time: '2 hrs ago',
    type: 'Care',
    details: 'Post-op pain assessment documented. Patient ambulated with assistance.',
  },
];

export const nurseDashboardService = {
  getNurseStats: async (): Promise<NurseStats> => {
    return Promise.resolve(NURSE_STATS);
  },
  getPatientQueue: async (): Promise<NurseQueuePatient[]> => {
    return Promise.resolve(NURSE_PATIENT_QUEUE);
  },
  getRecentVitals: async (): Promise<NurseVitalRecord[]> => {
    return Promise.resolve(RECENT_VITALS);
  },
  getNursingTasks: async (): Promise<NursingTask[]> => {
    return Promise.resolve(NURSING_TASKS);
  },
  getRecentAdmissions: async (): Promise<AdmissionRecord[]> => {
    return Promise.resolve(RECENT_ADMISSIONS);
  },
  getRecentActivities: async (): Promise<NursingActivity[]> => {
    return Promise.resolve(RECENT_NURSING_ACTIVITIES);
  },
};
